name: Format Python code with Black and auto-commit

on:
  push:
    branches: [main]  # o cambia con il branch che usi

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # serve per fare il commit automatico

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install black
        run: pip install black

      - name: Format code with black
        run: black .

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "🧹 Auto-format Python code with Black"
          git push
